import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import AppContext from '../appContext';
import { useState, useContext } from "react";
import AudioPlayer from '../components/AudioPlayer';

export default function player() {
    const context = useContext(AppContext)
    return (
        <>
            <Head>
                <title>Synesound Player</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div>

                    {context.imgUrl && <img src={context.imgUrl} />}
                </div>

                <div>
                    <h1>
                        Here's your synesound
                    </h1>
                </div>

                <div>
                    <AudioPlayer />
                </div>
                <div>

                    <Link href="/">Back to home</Link>
                </div>

            </main>
        </>

    );
}