import Head from "next/head";
import React from 'react';
import { useState, useContext } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { FileUpload } from "primereact/fileupload";
import Link from 'next/link';
import AppContext from "./appContext";
import Typewriter from 'typewriter-effect';

import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const context = useContext(AppContext)
  const onUpload = (event) => {
    console.log(event);
    const file = event.files[0].name;
    context.setImgUrl(`https://synesound-image.fra1.cdn.digitaloceanspaces.com/${file}`);

    // }
  };
  return (
    <>
      <Head>
        <title>Synesound</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <h1 className={styles.title}>SyneSound</h1>
           <h2>
               <Typewriter
                onInit={(typewriter) => {
                typewriter.typeString('Hi! :) I am Synesound. Welcome to your new experience')
                .callFunction(() => {
                console.log('String typed out!');
               })
               .pauseFor(2500)
               // .deleteAll()
               .callFunction(() => {
               // console.log('All strings were deleted');
               })
               .start();
              }}
               />
           </h2>

        <div className={styles.description}>
          
          <FileUpload
            name="demo"
            url={"/api/upload"}
            multiple
            accept="image/*"
            maxFileSize={1000000}
            emptyTemplate={
              <p className="m-0">Drag and drop files to here to upload.</p>
            }
            onUpload={onUpload}
          />
          {/* {context.imgUrl && <div><img src={context.imgUrl} /></div>} */}
        </div>

        <div>
          {/* <AudioPlayer /> */}
          <h2 className="animate-this" >
            <Link href="/posts/player">get</Link>
          </h2>
        </div>
      </main>
    </>
  );
}